### ISSUE TITLE
How does fuzzer and flipper mode work

### ISSUE THREAD

**Issue by LouisLiuNova** [tum-i22/macke#11]
The tutorial and the essay say Macke is combined with LLVM and AFL, but where? I tested all the files in `/macke/example` without AFL part and it succeeded. So how does Fuzzer work? How does it call AFL module? I couldn't find the critical part in source code.

Environment:
Ubuntu 64bits LTS16

**Comment by saahil** [comment]
Have you followed the entire step 2 (https://github.com/tum-i22/macke#step-2-building-the-macke-llvm-opt-passes)? This step will install the macke-fuzzer-opt-llvm in addition to macke-opt-llvm. Throughout this tutorial, we will assume that you have two versions of LLVM available on your system - LLVM 3.4 and LLVM 6.0. 

To run Macke in fuzzer or flipper mode, simply follow step 4 (https://github.com/tum-i22/macke#step-4-running-macke). You need to compile your C program twice - once with LLVM 3.4 (2beAnalyzed.bc) and once with LLVM 6.0 (2beAnalyzedCompiledWithClang3.8.bc). Then use the --fuzz-bc option to point to the second compiled object and finally give the path to the first compiled object. 

These above steps are necessary because the symbolic execution engine of Macke can only work with LLVM 3.4, while AFL can only work with LLVM 6.0 or above.

**Comment by LouisLiuNova** [comment]
Ok, but at the code level, in which function is the AFL called or started? What form of data or file is passed in? I want to track the AFL and other component calls but stop here.

**Comment by saahil** [comment]
> Ok, but at the code level, in which function is the AFL called or started? What form of data or file is passed in? I want to track the AFL and other component calls but stop here.

So you would only like to run the first phase of the analysis? In the Macke class (Macke.py) you can look at run_phase_one and run_phase_two to see how the two phases of analysis work (including calls to AFL, KLEE and, in case of flipper, both).
